[package]
name = "PDFcompressor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
lopdf = "0.32"
rfd = "0.15"
serde = { version = "1.0", features = ["derive"] }
image = "0.24"
flate2 = "1.0"
log = "0.4"
env_logger = "0.11"
